name: "Create Docker and JavaScript Actions"

on:
  pull_request:
    types: 
      - opened

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Post PR Comment
        uses: ./ # Assuming you have a custom action in the root of the repository
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}